### ISSUE TITLE
How to turning Push Notifications ON in Xcode

### ISSUE THREAD

**Issue by wann2** [duytq94/firebase-function-chat-demo#2]
Hi,

I'd like to implement Push Notifications ON in Xcode as your guide.
But the screen in my Xcode is different with your guide.
I can not turn on Push Notifications in my Xcode.
I have attached the screen capture of my xcode.

<img width="1403" alt="스크린샷 2020-05-01 16 03 58" src="https://user-images.githubusercontent.com/8732515/80789079-e67d2200-8bc5-11ea-8d74-f3c1b2757a28.png">

**Comment by duytq94** [comment]
Hi, did you have Paid Apple Developer account, you must have it to enable APN.
